
[program:voice-llama]
priority=10
command=/opt/floodman/unified/start-voice-llama.sh
autostart=true
autorestart=true
startsecs=8
startretries=5
stdout_logfile=/home/container/data/logs/llama.log
redirect_stderr=true
stdout_logfile_maxbytes=25MB
stdout_logfile_backups=3
stopasgroup=true
killasgroup=true

[program:voice-control]
priority=35
command=/opt/floodman/unified/start-voice-control.sh
autostart=true
autorestart=true
startsecs=10
startretries=5
stdout_logfile=/home/container/data/logs/appliance.log
redirect_stderr=true
stdout_logfile_maxbytes=25MB
stdout_logfile_backups=3
stopasgroup=true
killasgroup=true

[program:voice-asterisk]
priority=95
command=/opt/floodman/unified/start-voice-asterisk.sh
autostart=true
autorestart=true
startsecs=5
startretries=5
stdout_logfile=/home/container/data/logs/asterisk-console.log
redirect_stderr=true
stdout_logfile_maxbytes=25MB
stdout_logfile_backups=3
stopasgroup=true
killasgroup=true

[program:unified-public-gateway]
priority=90
command=/usr/sbin/nginx -e /home/container/data/business/logs/gateway-nginx.log -c /opt/floodman/unified/gateway-nginx.conf -g "daemon off;"
autostart=true
autorestart=true
startsecs=5
startretries=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true
