const state={token:sessionStorage.getItem('floodman_admin_token')||'',view:'dashboard',data:{}};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const titles={dashboard:'Overview',calls:'Call Gate',outbound:'Outbound Operations',campaigns:'Campaigns',crm:'Customers & Scheduling',billing:'Billing',compliance:'Consent & Suppression',outbox:'Roomflow Outbox',system:'System'};
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show${error?' error':''}`;setTimeout(()=>el.className='toast',3200)}
async function api(path,options={}){const headers={...(options.headers||{}),'Authorization':`Bearer ${state.token}`};if(options.body&&!headers['Content-Type'])headers['Content-Type']='application/json';const response=await fetch(path,{...options,headers});let data={};try{data=await response.json()}catch{data={detail:await response.text()}}if(!response.ok)throw new Error(data.detail||`Request failed (${response.status})`);return data}
function fmtDate(v){if(!v)return '—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString()}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function badge(v){const x=String(v||'unknown').toLowerCase();const cls=['ready','completed','active','ok','answered','scheduled','clear'].includes(x)?'good':['failed','blocked','security_block','canceled','suppressed'].includes(x)?'bad':'warn';return `<span class="badge ${cls}">${esc(v||'unknown')}</span>`}
function table(rows,columns,actions=''){if(!rows||!rows.length)return '<div class="empty">No records yet.</div>';return `<div class="table-wrap"><table><thead><tr>${columns.map(c=>`<th>${esc(c.label)}</th>`).join('')}${actions?'<th>Actions</th>':''}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(c=>`<td>${c.render?c.render(row):esc(row[c.key]??'—')}</td>`).join('')}${actions?`<td>${actions(row)}</td>`:''}</tr>`).join('')}</tbody></table></div>`}
function formObject(form){const data=Object.fromEntries(new FormData(form).entries());form.querySelectorAll('input[type=checkbox]').forEach(i=>data[i.name]=i.checked);return data}
function iso(v){return v?new Date(v).toISOString():null}
function showLogin(show){$('#login').classList.toggle('hidden',!show);$('#app').classList.toggle('hidden',show);if(show)$('#token').value=state.token}
async function login(){state.token=$('#token').value.trim();if(!state.token)return;try{await api('/api/v1/dashboard');sessionStorage.setItem('floodman_admin_token',state.token);showLogin(false);await loadAll()}catch(e){$('#loginError').textContent=e.message}}
function switchView(view){state.view=view;$$('.view').forEach(v=>v.classList.remove('active'));$(`#view-${view}`).classList.add('active');$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#pageTitle').textContent=titles[view]||view;window.scrollTo({top:0,behavior:'smooth'})}
async function loadAll(){try{const [dashboard,calls,jobs,campaigns,customers,appointments,callbacks,invoices,consents,suppressions,outbox,system]=await Promise.all([
api('/api/v1/dashboard'),api('/api/v1/gate/sessions?limit=100'),api('/api/v1/outbound/jobs?limit=200'),api('/api/v1/campaigns'),api('/api/v1/crm/customers?limit=200'),api('/api/v1/crm/appointments?limit=200'),api('/api/v1/crm/callbacks?limit=200'),api('/api/v1/crm/invoices?limit=200'),api('/api/v1/consents?limit=500'),api('/api/v1/suppressions'),api('/api/v1/outbox?limit=500'),api('/api/v1/system')]);state.data={dashboard,calls,jobs,campaigns,customers,appointments,callbacks,invoices,consents,suppressions,outbox,system};render();$('#healthDot').className='status-dot ok';$('#healthText').textContent='System online';$('#lastUpdated').textContent=`Updated ${new Date().toLocaleTimeString()}`}catch(e){if(/token|401|unauthorized/i.test(e.message)){sessionStorage.removeItem('floodman_admin_token');showLogin(true)}else{toast(e.message,true);$('#healthDot').className='status-dot bad';$('#healthText').textContent='Connection error'}}}
function render(){renderDashboard();renderCalls();renderOutbound();renderCampaigns();renderCRM();renderBilling();renderCompliance();renderOutbox();$('#systemJson').textContent=JSON.stringify(state.data.system,null,2)}
function renderDashboard(){const d=state.data.dashboard||{},c=d.counts||{};const metrics=[['Customers',c.customers],['Open leads',c.open_leads],['Upcoming visits',c.upcoming_appointments],['Open invoices',c.open_invoices],['Callbacks',c.open_callbacks],['Pending calls',c.outbound_pending],['Roomflow queue',c.outbox_pending],['Suppressed',c.suppressed_numbers],['Gate sessions',c.gate_sessions],['Completed calls',c.outbound_completed]];$('#metrics').innerHTML=metrics.map(([l,v])=>`<div class="metric"><span>${esc(l)}</span><strong>${Number(v||0).toLocaleString()}</strong><small>Live ledger</small></div>`).join('');const h=d.components||{},rows=[['Call gate',h.gate?.listening,h.gate?.transcriber],['Outbound worker',h.outbound?.enabled,h.outbound?.ami_enabled?'AMI connected/configured':'AMI disabled'],['Roomflow',h.roomflow?.enabled,h.roomflow?.configured?'Configured':'Local ledger active'],['Local CRM',h.local_crm?.enabled,'SQLite WAL']];$('#componentHealth').innerHTML=rows.map(([name,ok,detail])=>`<div class="health-row"><div><strong>${name}</strong><div class="muted">${esc(detail)}</div></div>${badge(ok?'online':'standby')}</div>`).join('');$('#recentEvents').innerHTML=(d.recent_events||[]).slice(0,12).map(e=>`<div class="timeline-item"><strong>${esc(e.event_type)}</strong><span>${fmtDate(e.created_at)} · ${esc(e.direction)}</span></div>`).join('')||'<div class="empty">No activity yet.</div>';$('#recentCalls').innerHTML=gateTable(d.recent_gate_sessions||[])}
function gateTable(rows){return table(rows,[{label:'Started',render:r=>fmtDate(r.created_at)},{label:'Caller',key:'caller_number'},{label:'Source',key:'source_hint'},{label:'Classification',render:r=>badge(r.classification)},{label:'Confidence',render:r=>`${Math.round(Number(r.confidence||0)*100)}%`},{label:'Agent',render:r=>`<code>${esc(r.agent)}</code>`},{label:'Opening transcript',render:r=>esc((r.opening_transcript||'').slice(0,180))}])}
function renderCalls(){$('#callsTable').innerHTML=gateTable(state.data.calls||[])}
function renderOutbound(){const actions=r=>`<div class="row-actions">${['pending','retry','failed','blocked'].includes(r.status)?`<button class="ghost" data-retry-job="${r.id}">Retry</button>`:''}${!['completed','canceled'].includes(r.status)?`<button class="danger" data-cancel-job="${r.id}">Cancel</button>`:''}</div>`;$('#outboundTable').innerHTML=table(state.data.jobs||[],[{label:'Scheduled',render:r=>fmtDate(r.scheduled_for)},{label:'Phone',key:'phone'},{label:'Purpose',key:'purpose'},{label:'Status',render:r=>badge(r.status)},{label:'Attempts',key:'attempts'},{label:'Agent',render:r=>`<code>${esc(r.agent)}</code>`},{label:'Reason',render:r=>esc(r.last_error||r.eligibility_reason||'—')}],actions)}
function renderCampaigns(){const rows=state.data.campaigns||[];const actions=r=>`<div class="row-actions"><button class="ghost" data-campaign-status="${r.id}" data-status="${r.status==='active'?'paused':'active'}">${r.status==='active'?'Pause':'Activate'}</button></div>`;$('#campaignsTable').innerHTML=table(rows,[{label:'Name',key:'name'},{label:'Purpose',key:'purpose'},{label:'Agent',render:r=>`<code>${esc(r.agent)}</code>`},{label:'Status',render:r=>badge(r.status)},{label:'Jobs',render:r=>`${Number(r.open_jobs||0)} open / ${Number(r.total_jobs||0)} total`},{label:'Created',render:r=>fmtDate(r.created_at)}],actions);const select=$('#campaignAudienceSelect');if(select){const prior=select.value;select.innerHTML=rows.map(r=>`<option value="${esc(r.id)}">${esc(r.name)} · ${esc(r.purpose)} · ${esc(r.status)}</option>`).join('')||'<option value="">Create a campaign first</option>';if(rows.some(r=>r.id===prior))select.value=prior}}
function renderCRM(){const q=($('#customerSearch')?.value||'').toLowerCase();const customers=(state.data.customers||[]).filter(r=>JSON.stringify(r).toLowerCase().includes(q));$('#customersTable').innerHTML=table(customers,[{label:'Name',key:'name'},{label:'Phone',key:'phone'},{label:'Email',key:'email'},{label:'Source',key:'source'},{label:'Customer ID',render:r=>`<code>${esc(r.id)}</code>`},{label:'Updated',render:r=>fmtDate(r.updated_at)}]);$('#appointmentsTable').innerHTML=table(state.data.appointments||[],[{label:'Start',render:r=>fmtDate(r.start_at)},{label:'Service',key:'service'},{label:'Status',render:r=>badge(r.status)},{label:'Customer',render:r=>`<code>${esc(r.customer_id)}</code>`}]);$('#callbacksTable').innerHTML=table(state.data.callbacks||[],[{label:'Created',render:r=>fmtDate(r.created_at)},{label:'Name',key:'name'},{label:'Phone',key:'phone'},{label:'Department',key:'department'},{label:'Urgency',render:r=>badge(r.urgency)},{label:'Reason',key:'reason'}])}
function renderBilling(){$('#invoicesTable').innerHTML=table(state.data.invoices||[],[{label:'Invoice',key:'invoice_number'},{label:'Customer',render:r=>`<code>${esc(r.customer_id)}</code>`},{label:'Due',render:r=>Number(r.amount_due||0).toLocaleString(undefined,{style:'currency',currency:r.currency||'USD'})},{label:'Status',render:r=>badge(r.status)},{label:'Due date',render:r=>fmtDate(r.due_date)},{label:'Payment link',render:r=>r.payment_url?'Configured':'—'}])}
function renderCompliance(){const suppressActions=r=>`<button class="ghost" data-unsuppress="${esc(r.phone)}">Remove</button>`;$('#consentsTable').innerHTML=table(state.data.consents||[],[{label:'Phone',key:'phone'},{label:'Customer',key:'customer_id'},{label:'Transactional',render:r=>badge(r.transactional_voice?'yes':'no')},{label:'Marketing written',render:r=>badge(r.marketing_voice_written?'yes':'no')},{label:'Source',key:'source'},{label:'Consented',render:r=>fmtDate(r.consented_at)},{label:'Revoked',render:r=>fmtDate(r.revoked_at)}]);$('#suppressionsTable').innerHTML=table(state.data.suppressions||[],[{label:'Phone',key:'phone'},{label:'Categories',render:r=>esc((r.categories||[]).join(', '))},{label:'Reason',key:'reason'},{label:'Source',key:'source'},{label:'Created',render:r=>fmtDate(r.created_at)}],suppressActions)}
function renderOutbox(){const actions=r=>r.status==='complete'?'':`<button class="ghost" data-retry-outbox="${r.id}">Retry</button>`;$('#outboxTable').innerHTML=table(state.data.outbox||[],[{label:'Created',render:r=>fmtDate(r.created_at)},{label:'Operation',render:r=>`<code>${esc(r.operation)}</code>`},{label:'Status',render:r=>badge(r.status)},{label:'Attempts',key:'attempts'},{label:'Next attempt',render:r=>fmtDate(r.next_attempt_at)},{label:'Error',render:r=>esc((r.last_error||'').slice(0,180))}],actions)}
async function submitJSON(form,path,transform=x=>x,resultEl){const data=transform(formObject(form));try{const result=await api(path,{method:'POST',body:JSON.stringify(data)});if(resultEl)$(resultEl).textContent=JSON.stringify(result,null,2);toast('Saved successfully');form.reset();await loadAll()}catch(e){toast(e.message,true);if(resultEl)$(resultEl).textContent=e.message}}
$('#loginButton').addEventListener('click',login);$('#token').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('#logoutButton').addEventListener('click',()=>{sessionStorage.removeItem('floodman_admin_token');state.token='';showLogin(true)});$('#refreshButton').addEventListener('click',loadAll);$$('#nav button').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$('#customerSearch').addEventListener('input',renderCRM);
$('#classifierForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/gate/classify',d=>({...d,elapsed_seconds:Number(d.elapsed_seconds||0)}),'#classifierResult')});
$('#testCallForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/test-calls/outbound',d=>({...d,label:d.label||'production_audio_test'}),'#testCallResult')});
$('#outboundForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/outbound/jobs',d=>({...d,scheduled_for:iso(d.scheduled_for)||new Date().toISOString(),requested_at:iso(d.requested_at),payload:{source:'admin_panel'}}),'#outboundResult')});
$('#campaignForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/campaigns')});
$('#campaignEnqueueForm').addEventListener('submit',e=>{e.preventDefault();const d=formObject(e.currentTarget);const entries=(d.audience||'').split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map(line=>{const [phone,customer_id='',timezone='America/Detroit']=line.split(',').map(x=>x.trim());return{phone,customer_id,timezone,payload:{}}});const common_payload={dnc_status:d.dnc_status||'',dnc_checked_at:iso(d.dnc_checked_at),reassignment_status:d.reassignment_status||'',reassignment_checked_at:iso(d.reassignment_checked_at)};submitJSON(e.currentTarget,`/api/v1/campaigns/${encodeURIComponent(d.campaign_id)}/enqueue`,()=>({entries,start_at:iso(d.start_at)||new Date().toISOString(),spacing_seconds:Number(d.spacing_seconds||20),common_payload}),'#campaignEnqueueResult')});
$('#customerForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/crm/customers')});
$('#invoiceForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/crm/invoices',d=>({...d,amount_due:Number(d.amount_due||0),due_date:d.due_date?new Date(`${d.due_date}T12:00:00`).toISOString():null}))});
$('#consentForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/consents',d=>({...d,consented_at:new Date().toISOString(),raw:{source:'admin_panel'}}))});
$('#suppressionForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/suppressions',d=>({...d,categories:d.categories.split(',').map(x=>x.trim()).filter(Boolean),source:'admin_panel'}))});
document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;try{if(t.dataset.retryJob)await api(`/api/v1/outbound/jobs/${t.dataset.retryJob}/retry`,{method:'POST'});else if(t.dataset.cancelJob)await api(`/api/v1/outbound/jobs/${t.dataset.cancelJob}/cancel`,{method:'POST'});else if(t.dataset.campaignStatus)await api(`/api/v1/campaigns/${t.dataset.campaignStatus}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:t.dataset.status})});else if(t.dataset.unsuppress)await api(`/api/v1/suppressions/${encodeURIComponent(t.dataset.unsuppress)}`,{method:'DELETE'});else if(t.dataset.retryOutbox)await api(`/api/v1/outbox/${t.dataset.retryOutbox}/retry`,{method:'POST'});else return;toast('Action completed');await loadAll()}catch(err){toast(err.message,true)}});
if(state.token){showLogin(false);loadAll()}else showLogin(true);
