const state={
  token:sessionStorage.getItem('floodman_admin_token')||'',
  view:'dashboard',
  data:{},
  selectedCustomerId:sessionStorage.getItem('floodman_selected_customer')||'',
  customerBundle:null,
  customerPickerOpen:!sessionStorage.getItem('floodman_selected_customer'),
  billingCustomerId:sessionStorage.getItem('floodman_billing_customer')||'',
  editingProperty:null
};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const titles={dashboard:'Overview',calls:'Calls',outbound:'Outbound Calls',campaigns:'Campaigns',crm:'Customers',billing:'Billing',compliance:'Consent & Suppression',outbox:'Roomflow Sync',system:'System'};
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show${error?' error':''}`;setTimeout(()=>el.className='toast',3200)}
async function api(path,options={}){const headers={...(options.headers||{}),'Authorization':`Bearer ${state.token}`};if(options.body&&!headers['Content-Type'])headers['Content-Type']='application/json';const response=await fetch(path,{...options,headers});let data={};try{data=await response.json()}catch{data={detail:await response.text()}}if(!response.ok)throw new Error(data.detail||`Request failed (${response.status})`);return data}
function fmtDate(v){if(!v)return '—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString()}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function badge(v){const x=String(v||'unknown').toLowerCase();const cls=['ready','completed','complete','supported','active','ok','answered','scheduled','clear','queued'].includes(x)?'good':['failed','blocked','security_block','canceled','suppressed','unsupported','partial_provider_failure'].includes(x)?'bad':'warn';return `<span class="badge ${cls}">${esc(v||'unknown')}</span>`}
function table(rows,columns,actions=''){if(!rows||!rows.length)return '<div class="empty">No records yet.</div>';return `<div class="table-wrap"><table><thead><tr>${columns.map(c=>`<th>${esc(c.label)}</th>`).join('')}${actions?'<th>Actions</th>':''}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(c=>`<td>${c.render?c.render(row):esc(row[c.key]??'—')}</td>`).join('')}${actions?`<td>${actions(row)}</td>`:''}</tr>`).join('')}</tbody></table></div>`}
function formObject(form){const data=Object.fromEntries(new FormData(form).entries());form.querySelectorAll('input[type=checkbox]').forEach(i=>data[i.name]=i.checked);return data}
function iso(v){return v?new Date(v).toISOString():null}
function showLogin(show){$('#login').classList.toggle('hidden',!show);$('#app').classList.toggle('hidden',show);if(show)$('#token').value=state.token}
async function login(){state.token=$('#token').value.trim();if(!state.token)return;try{await api('/api/v1/dashboard');sessionStorage.setItem('floodman_admin_token',state.token);showLogin(false);await loadAll()}catch(e){$('#loginError').textContent=e.message}}
function switchView(view){state.view=view;$$('.view').forEach(v=>v.classList.remove('active'));$(`#view-${view}`).classList.add('active');$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(['outbound','campaigns','compliance','outbox','system'].includes(view))$('#moreToolsNav').open=true;$('#pageTitle').textContent=titles[view]||view;window.scrollTo({top:0,behavior:'smooth'})}
async function loadAll(){try{const [dashboard,calls,intakes,jobs,campaigns,customers,appointments,callbacks,invoices,consents,suppressions,outbox,system]=await Promise.all([
api('/api/v1/dashboard'),api('/api/v1/gate/sessions?limit=100'),api('/api/v1/call-intakes?limit=200'),api('/api/v1/outbound/jobs?limit=200'),api('/api/v1/campaigns'),api('/api/v1/crm/customers?limit=200'),api('/api/v1/crm/appointments?limit=200'),api('/api/v1/crm/callbacks?limit=200'),api('/api/v1/crm/invoices?limit=200'),api('/api/v1/consents?limit=500'),api('/api/v1/suppressions'),api('/api/v1/outbox?limit=500'),api('/api/v1/system')]);state.data={dashboard,calls,intakes,jobs,campaigns,customers,appointments,callbacks,invoices,consents,suppressions,outbox,system};if(state.selectedCustomerId){if(customers.some(customer=>customer.id===state.selectedCustomerId)){state.customerBundle=await api(`/api/v1/crm/customers/${encodeURIComponent(state.selectedCustomerId)}`)}else{clearSelectedCustomer()}}render();$('#healthDot').className='status-dot ok';$('#healthText').textContent='System online';$('#lastUpdated').textContent=`Updated ${new Date().toLocaleTimeString()}`}catch(e){if(/token|401|unauthorized/i.test(e.message)){sessionStorage.removeItem('floodman_admin_token');showLogin(true)}else{toast(e.message,true);$('#healthDot').className='status-dot bad';$('#healthText').textContent='Connection error'}}}
function render(){renderDashboard();renderCalls();renderOutbound();renderCampaigns();renderCRM();renderBilling();renderCompliance();renderOutbox();$('#systemJson').textContent=JSON.stringify(state.data.system,null,2)}
function renderDashboard(){const d=state.data.dashboard||{},c=d.counts||{};const metrics=[['Calls received',c.call_intakes],['Customers',c.customers],['Upcoming visits',c.upcoming_appointments],['Open invoices',c.open_invoices],['Callbacks',c.open_callbacks]];$('#metrics').innerHTML=metrics.map(([l,v])=>`<div class="metric"><span>${esc(l)}</span><strong>${Number(v||0).toLocaleString()}</strong></div>`).join('');const h=d.components||{},rows=[['Call system',h.gate?.listening,h.gate?.listening?'Ready':'Needs attention'],['Outbound calls',h.outbound?.enabled,h.outbound?.enabled?'Ready':'Standby'],['Roomflow',h.roomflow?.enabled,h.roomflow?.configured?'Connected':'Local records active'],['Customer records',h.local_crm?.enabled,'Ready']];$('#componentHealth').innerHTML=rows.map(([name,ok,detail])=>`<div class="health-row"><div><strong>${name}</strong><div class="muted">${esc(detail)}</div></div>${badge(ok?'online':'standby')}</div>`).join('');$('#recentEvents').innerHTML=(d.recent_events||[]).slice(0,8).map(e=>`<div class="timeline-item"><strong>${esc(String(e.event_type||'Activity').replaceAll('_',' '))}</strong><span>${fmtDate(e.created_at)}</span></div>`).join('')||'<div class="empty">No activity yet.</div>';$('#recentCalls').innerHTML=gateTable((d.recent_gate_sessions||[]).slice(0,8))}
function gateTable(rows){return table(rows,[{label:'Started',render:r=>fmtDate(r.created_at)},{label:'Caller',key:'caller_number'},{label:'Result',render:r=>badge(r.classification)},{label:'Opening',render:r=>esc((r.opening_transcript||'No opening captured').slice(0,120))}])}
function diagnosticGateTable(rows){return table(rows,[{label:'Started',render:r=>fmtDate(r.created_at)},{label:'Caller',key:'caller_number'},{label:'Source',key:'source_hint'},{label:'Classification',render:r=>badge(r.classification)},{label:'Confidence',render:r=>`${Math.round(Number(r.confidence||0)*100)}%`},{label:'Agent',render:r=>`<code>${esc(r.agent)}</code>`}])}
function intakeRows(){const value=state.data.intakes||{};return Array.isArray(value)?value:(value.intakes||[])}
function intakeStatus(r){const status=String(r.status||'collecting').replaceAll('_',' ');const service=String(r.service_status||'unknown').replaceAll('_',' ');return `${badge(status)} ${badge(service)}`}
function renderCalls(){
  const q=($('#callSearch')?.value||'').trim().toLowerCase();
  const rows=intakeRows().filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q));
  const actions=r=>`<button class="ghost" data-call-detail="${esc(r.call_id)}">View details</button>`;
  $('#intakesTable').innerHTML=table(rows,[
    {label:'Received',render:r=>fmtDate(r.created_at)},
    {label:'Caller',render:r=>`<strong>${esc(r.name||'Unknown caller')}</strong><div class="muted">${esc(r.phone||r.caller_number||'Unavailable')}</div>`},
    {label:'Property',render:r=>esc((r.address||'Not supplied').slice(0,120))},
    {label:'Service',render:r=>esc(r.service_requested||'Not identified')},
    {label:'Status',render:intakeStatus},
  ],actions);
  $('#gateDiagnosticsTable').innerHTML=diagnosticGateTable(state.data.calls||[]);
}
function detailField(label,value){const shown=String(value??'').trim();return `<div class="detail-field"><span>${esc(label)}</span><strong>${esc(shown||'Not supplied')}</strong></div>`}
function transcriptFromPayload(intake){if(intake.transcript_text)return String(intake.transcript_text);const value=intake.transcript;if(!value)return 'No transcript was returned.';if(typeof value==='string')return value;try{return value.map(item=>{const role=String(item.role||item.speaker||'Conversation').toLowerCase();const label=['user','caller','customer','human'].includes(role)?'Caller':['assistant','agent','ava','ai'].includes(role)?'Ava':role;const content=item.content??item.text??item.transcript??item.message??'';const text=typeof content==='string'?content:JSON.stringify(content);return `${label}: ${text}`}).join('\n')}catch{return JSON.stringify(value,null,2)}}
async function openCallDetail(callId){
  try{
    const result=await api(`/api/v1/call-intakes/${encodeURIComponent(callId)}`);
    const r=result.intake||{};
    $('#callDetailTitle').textContent=r.name?`${r.name} · ${r.call_id}`:`Call ${r.call_id||callId}`;
    $('#callDetailBody').innerHTML=[
      detailField('Call status',String(r.status||'collecting').replaceAll('_',' ')),
      detailField('Service review',String(r.service_status||'unknown').replaceAll('_',' ')),
      detailField('Name',r.name),detailField('Phone',r.phone||r.caller_number),detailField('Email',r.email||r.email_status),
      detailField('Property address',r.address),detailField('Requested service',r.service_requested),detailField('Urgency',r.urgency),
      detailField('What is happening',r.description),detailField('Property context',r.property_context),detailField('Safety details',r.safety_summary),
      detailField('Timing and activity',r.timing_summary),detailField('Insurance / previous work',r.insurance_summary),detailField('Photos / referral source',r.evidence_summary),
      detailField('Team notification',Number(r.notification_count||0)>0?`${r.notification_count} queued`:'Not queued'),detailField('Outcome',r.outcome),detailField('Summary',r.summary)
    ].join('');
    $('#callTranscript').textContent=transcriptFromPayload(r);
    $('#callEventTimeline').innerHTML=(result.events||[]).map(e=>`<div class="timeline-item"><strong>${esc(e.event_type)}</strong><span>${fmtDate(e.created_at)} · ${esc(JSON.stringify(e.payload||{}).slice(0,400))}</span></div>`).join('')||'<div class="empty">No call events were recorded.</div>';
    const dialog=$('#callDetailDialog');
    if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');
  }catch(error){toast(error.message,true)}
}
function customerOptions(blankLabel='Select a customer'){const customers=state.data.customers||[];return `<option value="">${esc(blankLabel)}</option>${customers.map(customer=>`<option value="${esc(customer.id)}">${esc(customer.name||'Unnamed customer')}${customer.phone?` · ${esc(customer.phone)}`:''}</option>`).join('')}`}
function fillCustomerSelect(selector,{blankLabel='Select a customer',preferred=''}={}){const select=$(selector);if(!select)return;const prior=select.value;select.innerHTML=customerOptions(blankLabel);const next=[prior,preferred,state.selectedCustomerId].find(value=>value&&[...select.options].some(option=>option.value===value));if(next)select.value=next}
function customerById(customerId){return (state.data.customers||[]).find(customer=>customer.id===customerId)||null}
function renderOutbound(){fillCustomerSelect('#outboundCustomerSelect');const selected=customerById($('#outboundCustomerSelect').value);if(selected?.phone&&!$('#outboundPhone').value)$('#outboundPhone').value=selected.phone;const actions=r=>`<div class="row-actions">${['pending','retry','failed','blocked'].includes(r.status)?`<button class="ghost" data-retry-job="${r.id}">Retry</button>`:''}${!['completed','canceled'].includes(r.status)?`<button class="danger" data-cancel-job="${r.id}">Cancel</button>`:''}</div>`;$('#outboundTable').innerHTML=table(state.data.jobs||[],[{label:'Call at',render:r=>fmtDate(r.scheduled_for)},{label:'Phone',key:'phone'},{label:'Reason',render:r=>esc(String(r.purpose||'').replaceAll('_',' '))},{label:'Status',render:r=>badge(r.status)}],actions)}
function renderCampaigns(){const rows=state.data.campaigns||[];const actions=r=>`<div class="row-actions"><button class="ghost" data-campaign-status="${r.id}" data-status="${r.status==='active'?'paused':'active'}">${r.status==='active'?'Pause':'Activate'}</button></div>`;$('#campaignsTable').innerHTML=table(rows,[{label:'Name',key:'name'},{label:'Purpose',key:'purpose'},{label:'Agent',render:r=>`<code>${esc(r.agent)}</code>`},{label:'Status',render:r=>badge(r.status)},{label:'Jobs',render:r=>`${Number(r.open_jobs||0)} open / ${Number(r.total_jobs||0)} total`},{label:'Created',render:r=>fmtDate(r.created_at)}],actions);const select=$('#campaignAudienceSelect');if(select){const prior=select.value;select.innerHTML=rows.map(r=>`<option value="${esc(r.id)}">${esc(r.name)} · ${esc(r.purpose)} · ${esc(r.status)}</option>`).join('')||'<option value="">Create a campaign first</option>';if(rows.some(r=>r.id===prior))select.value=prior}}
function clearSelectedCustomer(){state.selectedCustomerId='';state.customerBundle=null;state.customerPickerOpen=true;sessionStorage.removeItem('floodman_selected_customer')}
async function selectCustomer(customerId){if(!customerId){clearSelectedCustomer();renderCRM();return}try{if(state.selectedCustomerId&&state.selectedCustomerId!==customerId){resetCustomerEditor();resetPropertyEditor()}state.selectedCustomerId=customerId;state.customerPickerOpen=false;sessionStorage.setItem('floodman_selected_customer',customerId);state.customerBundle=await api(`/api/v1/crm/customers/${encodeURIComponent(customerId)}`);if(!state.billingCustomerId){state.billingCustomerId=customerId;sessionStorage.setItem('floodman_billing_customer',customerId)}renderCRM();renderBilling();renderOutbound();renderCompliance()}catch(error){clearSelectedCustomer();renderCRM();toast(error.message,true)}}
function selectedCustomer(){return state.customerBundle&&state.customerBundle.id===state.selectedCustomerId?state.customerBundle:null}
function renderCRM(){
  const q=($('#customerSearch')?.value||'').trim().toLowerCase();
  const customers=(state.data.customers||[]).filter(customer=>!q||[customer.name,customer.phone,customer.email].some(value=>String(value||'').toLowerCase().includes(q)));
  const selected=selectedCustomer();
  $('#customerPickerPanel').classList.toggle('hidden',Boolean(selected)&&!state.customerPickerOpen);
  $('#customerWorkspace').classList.toggle('hidden',!selected||state.customerPickerOpen);
  $('#customerEditor').classList.toggle('hidden',Boolean(selected)&&!$('#customerEditor').open);
  const actions=customer=>`<button class="primary tiny" data-select-customer="${esc(customer.id)}">Open</button>`;
  $('#customersTable').innerHTML=table(customers,[
    {label:'Customer',render:customer=>`<strong>${esc(customer.name||'Unnamed customer')}</strong>${customer.email?`<div class="muted">${esc(customer.email)}</div>`:''}`},
    {label:'Phone',render:customer=>esc(customer.phone||'Not supplied')},
    {label:'Updated',render:customer=>fmtDate(customer.updated_at)}
  ],actions);
  if(!selected)return;
  $('#propertyEditor').classList.toggle('hidden',!$('#propertyEditor').open);
  const properties=selected.properties||[];
  const openInvoices=(selected.invoices||[]).filter(invoice=>!['paid','void','canceled'].includes(String(invoice.status||'').toLowerCase()));
  $('#selectedCustomerSummary').innerHTML=`<p class="eyebrow">SELECTED CUSTOMER</p><h3>${esc(selected.name||'Unnamed customer')}</h3><div class="customer-contact"><span>${esc(selected.phone||'No phone')}</span><span>${esc(selected.email||'No email')}</span><span>${properties.length} ${properties.length===1?'property':'properties'}</span><span>${openInvoices.length} open ${openInvoices.length===1?'invoice':'invoices'}</span></div>`;
  const propertyActions=property=>`<button class="ghost tiny" data-edit-property="${esc(property.id)}">Edit</button>`;
  $('#propertiesTable').innerHTML=table(properties,[
    {label:'Address',render:property=>`<strong>${esc(property.address)}</strong><div class="muted">${esc([property.city,property.state,property.zip].filter(Boolean).join(', '))}</div>`},
    {label:'Notes',render:property=>esc(property.notes||'—')},
    {label:'Updated',render:property=>fmtDate(property.updated_at)}
  ],propertyActions);
  $('#appointmentsTable').innerHTML=table(selected.appointments||[],[{label:'When',render:item=>fmtDate(item.start_at)},{label:'Service',key:'service'},{label:'Status',render:item=>badge(item.status)}]);
  $('#callbacksTable').innerHTML=table(selected.callbacks||[],[{label:'Created',render:item=>fmtDate(item.created_at)},{label:'Reason',key:'reason'},{label:'Urgency',render:item=>badge(item.urgency)},{label:'Status',render:item=>badge(item.status)}]);
  const propertyCustomer=$('#propertyForm [name=customer_id]');if(propertyCustomer)propertyCustomer.value=selected.id;
}
function renderBilling(){fillCustomerSelect('#billingCustomerSelect',{preferred:state.billingCustomerId});const select=$('#billingCustomerSelect');const customerId=select?.value||'';state.billingCustomerId=customerId;if(customerId)sessionStorage.setItem('floodman_billing_customer',customerId);else sessionStorage.removeItem('floodman_billing_customer');const customer=customerById(customerId);$('#billingCustomerHint').textContent=customer?`Showing invoices for ${customer.name}.`:'Select a customer to view invoices.';const rows=customerId?(state.data.invoices||[]).filter(invoice=>invoice.customer_id===customerId):[];$('#invoicesTable').innerHTML=table(rows,[{label:'Invoice',key:'invoice_number'},{label:'Amount due',render:r=>Number(r.amount_due||0).toLocaleString(undefined,{style:'currency',currency:r.currency||'USD'})},{label:'Status',render:r=>badge(r.status)},{label:'Due date',render:r=>fmtDate(r.due_date)},{label:'Payment link',render:r=>r.payment_url?'Ready':'—'}])}
function renderCompliance(){fillCustomerSelect('#consentCustomerSelect');const selected=customerById($('#consentCustomerSelect').value);if(selected?.phone&&!$('#consentPhone').value)$('#consentPhone').value=selected.phone;const suppressActions=r=>`<button class="ghost" data-unsuppress="${esc(r.phone)}">Remove</button>`;$('#consentsTable').innerHTML=table(state.data.consents||[],[{label:'Phone',key:'phone'},{label:'Customer',render:r=>esc(customerById(r.customer_id)?.name||'—')},{label:'Voice',render:r=>badge(r.transactional_voice?'yes':'no')},{label:'Marketing',render:r=>badge(r.marketing_voice_written?'yes':'no')},{label:'Source',key:'source'},{label:'Consented',render:r=>fmtDate(r.consented_at)}]);$('#suppressionsTable').innerHTML=table(state.data.suppressions||[],[{label:'Phone',key:'phone'},{label:'Categories',render:r=>esc((r.categories||[]).join(', '))},{label:'Reason',key:'reason'},{label:'Created',render:r=>fmtDate(r.created_at)}],suppressActions)}
function renderOutbox(){const actions=r=>r.status==='complete'?'':`<button class="ghost" data-retry-outbox="${r.id}">Retry</button>`;$('#outboxTable').innerHTML=table(state.data.outbox||[],[{label:'Created',render:r=>fmtDate(r.created_at)},{label:'Operation',render:r=>`<code>${esc(r.operation)}</code>`},{label:'Status',render:r=>badge(r.status)},{label:'Attempts',key:'attempts'},{label:'Next attempt',render:r=>fmtDate(r.next_attempt_at)},{label:'Error',render:r=>esc((r.last_error||'').slice(0,180))}],actions)}
async function submitJSON(form,path,transform=x=>x,resultEl){const data=transform(formObject(form));try{const result=await api(path,{method:'POST',body:JSON.stringify(data)});if(resultEl)$(resultEl).textContent=JSON.stringify(result,null,2);toast('Saved successfully');form.reset();await loadAll();return result}catch(e){toast(e.message,true);if(resultEl)$(resultEl).textContent=e.message;return null}}
function resetCustomerEditor(){const form=$('#customerForm');form.reset();form.elements.id.value='';$('#customerEditorLabel').textContent='Add customer';$('#customerEditor').open=false;$('#customerEditor').classList.toggle('hidden',Boolean(selectedCustomer()))}
function openCustomerEditor(customer=null){const form=$('#customerForm');form.reset();form.elements.id.value=customer?.id||'';form.elements.name.value=customer?.name||'';form.elements.phone.value=customer?.phone||'';form.elements.email.value=customer?.email||'';$('#customerEditorLabel').textContent=customer?'Edit customer':'Add customer';$('#customerEditor').classList.remove('hidden');$('#customerEditor').open=true;$('#customerEditor').scrollIntoView({behavior:'smooth',block:'center'})}
function resetPropertyEditor(){const form=$('#propertyForm');form.reset();form.elements.id.value='';form.elements.customer_id.value=state.selectedCustomerId;form.elements.state.value='MI';state.editingProperty=null;$('#propertyEditorLabel').textContent='Add property';$('#propertyEditor').open=false;$('#propertyEditor').classList.add('hidden')}
function openPropertyEditor(property=null){const form=$('#propertyForm');form.reset();form.elements.id.value=property?.id||'';form.elements.customer_id.value=state.selectedCustomerId;form.elements.address.value=property?.address||'';form.elements.city.value=property?.city||'';form.elements.state.value=property?.state||'MI';form.elements.zip.value=property?.zip||'';form.elements.notes.value=property?.notes||'';state.editingProperty=property;$('#propertyEditorLabel').textContent=property?'Edit property':'Add property';$('#propertyEditor').classList.remove('hidden');$('#propertyEditor').open=true;$('#propertyEditor').scrollIntoView({behavior:'smooth',block:'center'})}
$('#loginButton').addEventListener('click',login);$('#token').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('#logoutButton').addEventListener('click',()=>{sessionStorage.removeItem('floodman_admin_token');state.token='';showLogin(true)});$('#refreshButton').addEventListener('click',loadAll);$$('#nav button').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$('#customerSearch').addEventListener('input',renderCRM);$('#callSearch')?.addEventListener('input',renderCalls);
$('#classifierForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/gate/classify',d=>({...d,elapsed_seconds:Number(d.elapsed_seconds||0)}),'#classifierResult')});
$('#testCallForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/test-calls/outbound',d=>({...d,label:d.label||'production_audio_test'}),'#testCallResult')});
$('#outboundForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/outbound/jobs',d=>({...d,scheduled_for:iso(d.scheduled_for)||new Date().toISOString(),requested_at:null,timezone:'America/Detroit',payload:{source:'admin_panel'}}),'#outboundResult')});
$('#campaignForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/campaigns')});
$('#campaignEnqueueForm').addEventListener('submit',e=>{e.preventDefault();const d=formObject(e.currentTarget);const entries=(d.audience||'').split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map(line=>{const [phone,customer_id='',timezone='America/Detroit']=line.split(',').map(x=>x.trim());return{phone,customer_id,timezone,payload:{}}});const common_payload={dnc_status:d.dnc_status||'',dnc_checked_at:iso(d.dnc_checked_at),reassignment_status:d.reassignment_status||'',reassignment_checked_at:iso(d.reassignment_checked_at)};submitJSON(e.currentTarget,`/api/v1/campaigns/${encodeURIComponent(d.campaign_id)}/enqueue`,()=>({entries,start_at:iso(d.start_at)||new Date().toISOString(),spacing_seconds:Number(d.spacing_seconds||20),common_payload}),'#campaignEnqueueResult')});
$('#customerForm').addEventListener('submit',async e=>{e.preventDefault();const editingId=e.currentTarget.elements.id.value;const editing=editingId?(customerById(editingId)||selectedCustomer()):null;const result=await submitJSON(e.currentTarget,'/api/v1/crm/customers',d=>({...d,external_id:editing?.external_id||'',source:editing?.source||'manual',metadata:editing?.metadata||{}}));if(result?.id){resetCustomerEditor();await selectCustomer(result.id)}});
$('#propertyForm').addEventListener('submit',async e=>{e.preventDefault();const editing=state.editingProperty;const result=await submitJSON(e.currentTarget,'/api/v1/crm/properties',d=>({...d,external_id:editing?.external_id||'',metadata:editing?.metadata||{}}));if(result?.id){resetPropertyEditor();await selectCustomer(result.customer_id)}});
$('#invoiceForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/crm/invoices',d=>({...d,amount_due:Number(d.amount_due||0),due_date:d.due_date?new Date(`${d.due_date}T12:00:00`).toISOString():null}))});
$('#consentForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/consents',d=>({...d,consented_at:new Date().toISOString(),raw:{source:'admin_panel'}}))});
$('#suppressionForm').addEventListener('submit',e=>{e.preventDefault();submitJSON(e.currentTarget,'/api/v1/suppressions',d=>({...d,categories:d.categories.split(',').map(x=>x.trim()).filter(Boolean),source:'admin_panel'}))});
$('#billingCustomerSelect').addEventListener('change',e=>{state.billingCustomerId=e.currentTarget.value;renderBilling()});
$('#outboundCustomerSelect').addEventListener('change',e=>{const customer=customerById(e.currentTarget.value);if(customer?.phone)$('#outboundPhone').value=customer.phone});
$('#consentCustomerSelect').addEventListener('change',e=>{const customer=customerById(e.currentTarget.value);if(customer?.phone)$('#consentPhone').value=customer.phone});
document.addEventListener('click',async e=>{const viewLink=e.target.closest('[data-view-link]');if(viewLink){switchView(viewLink.dataset.viewLink);return}const select=e.target.closest('[data-select-customer]');if(select){await selectCustomer(select.dataset.selectCustomer);return}if(e.target.closest('[data-change-customer]')){state.customerPickerOpen=true;renderCRM();return}if(e.target.closest('[data-new-customer]')){openCustomerEditor();return}if(e.target.closest('[data-edit-customer]')){openCustomerEditor(selectedCustomer());return}if(e.target.closest('[data-cancel-customer-edit]')){resetCustomerEditor();return}if(e.target.closest('[data-new-property]')){openPropertyEditor();return}const editProperty=e.target.closest('[data-edit-property]');if(editProperty){const property=(selectedCustomer()?.properties||[]).find(item=>item.id===editProperty.dataset.editProperty);if(property)openPropertyEditor(property);return}if(e.target.closest('[data-cancel-property-edit]')){resetPropertyEditor();return}const detail=e.target.closest('[data-call-detail]');if(detail){await openCallDetail(detail.dataset.callDetail);return}const close=e.target.closest('[data-close-call-detail]');if(close){const dialog=$('#callDetailDialog');if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open')}});
document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;try{if(t.dataset.retryJob)await api(`/api/v1/outbound/jobs/${t.dataset.retryJob}/retry`,{method:'POST'});else if(t.dataset.cancelJob)await api(`/api/v1/outbound/jobs/${t.dataset.cancelJob}/cancel`,{method:'POST'});else if(t.dataset.campaignStatus)await api(`/api/v1/campaigns/${t.dataset.campaignStatus}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:t.dataset.status})});else if(t.dataset.unsuppress)await api(`/api/v1/suppressions/${encodeURIComponent(t.dataset.unsuppress)}`,{method:'DELETE'});else if(t.dataset.retryOutbox)await api(`/api/v1/outbox/${t.dataset.retryOutbox}/retry`,{method:'POST'});else return;toast('Action completed');await loadAll()}catch(err){toast(err.message,true)}});
if(state.token){showLogin(false);loadAll()}else showLogin(true);
